name: 'sort completed fics'
on:
    workflow_dispatch:
    schedule: ## Schedule the job to run at 12.am daily.
        - cron: '0 8 * * *'

jobs:
    pythonJob:
        name: pythonFile
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v1
        - uses: BSFishy/pip-action@v1
          with:
            packages: |
              alive_progress
              re
        - name: runfile
          env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            
          run: python sortCompletedFics.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
          shell: sh

    